name: Deploy Lambda via Docker

on:
  push:
    branches:
      - main  # ou outra branch de produção

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login na AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login no Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 932769097131.dkr.ecr.us-east-1.amazonaws.com

      - name: Build da imagem Docker
        run: |
          docker build -t fast_lambda .

      - name: Tag e push da imagem para o ECR
        run: |
          docker tag fast_lambda:latest 932769097131.dkr.ecr.us-east-1.amazonaws.com/evandro:latest
          docker push 932769097131.dkr.ecr.us-east-1.amazonaws.com/evandro:latest

      - name: Atualiza função Lambda
        run: |
          aws lambda update-function-code \
            --function-name fast_lambda \
            --image-uri 932769097131.dkr.ecr.us-east-1.amazonaws.com/evandro:latest
